/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_i2c.h"
#include "fsl_lpadc.h"
#include "fsl_reset.h"
#include "fsl_usart.h"
#include "fsl_clock.h"
#include "fsl_gpio.h"
#include "fsl_utick.h"
#include "fsl_wwdt.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for FLEXCOMM0 */
/* Definition of peripheral ID */
#define FLEXCOMM0_PERIPHERAL ((I2C_Type *)FLEXCOMM0)
/* Definition of the clock source frequency */
#define FLEXCOMM0_CLOCK_SOURCE 12000000UL
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Definition of peripheral ID */
#define PLU_PERIPHERAL PLU
/* PLU_WAKEINT_CTRL: LATCH_ENABLE=0, FILTER_MODE=0, MASK=0 */
#define PLU_WAKEINT_CTRL_INIT 0x0U
/* SCT unified counter input clock frequency */
#define SCT0_CLK_FREQ 150000000UL
/* SCT unified counter input clock period in ns */
#define SCT0_CLK_PERIOD 7UL
/* State 0 - STATE_0 */
#define SCT0_STATE_0 0U
/* SCT0_CONFIG: NORELOAD_L=0, CLKMODE=0, UNIFY=1 */
#define SCT0_CONFIG_INIT 0x1E01U
/* SCT0_CTRL: PRE_L=0, BIDIR_L=0, HALT_L=1, STOP_L=0 */
#define SCT0_CTRL_INIT 0x40004U
/* SCT0_COUNT: CTR_H=0, CTR_L=0 */
#define SCT0_COUNT_INIT 0x0U
/* SCT0_STATE: STATE_L=0 */
#define SCT0_STATE_INIT 0x0U
/* SCT0_DMAREQ0: DRL0=0 */
#define SCT0_DMAREQ0_INIT 0x0U
/* SCT0_DMAREQ1: DRL1=0 */
#define SCT0_DMAREQ1_INIT 0x0U
/* Definition of peripheral ID */
#define FLEXCOMM1_PERIPHERAL ((USART_Type *)FLEXCOMM1)
/* Definition of the clock source frequency */
#define FLEXCOMM1_CLOCK_SOURCE 12000000UL
/* Definition of peripheral ID */
#define FLEXCOMM2_PERIPHERAL ((USART_Type *)FLEXCOMM2)
/* Definition of the clock source frequency */
#define FLEXCOMM2_CLOCK_SOURCE 12000000UL
/* Definition of peripheral ID */
#define GPIO_GPIO GPIO
/* BOARD_InitPeripherals defines for UTICK0 */
/* Definition of peripheral ID */
#define UTICK0_PERIPHERAL UTICK0
/* Definition of kUTICK_Onetime operational mode */
#define UTICK0_MODE kUTICK_Onetime
/* Timer tick frequency in Hz (input frequency of the timer) */
#define UTICK0_TICK_FREQ 1000000UL
/* Timer tick period in ns (input period of the timer) */
#define UTICK0_TICK_PERIOD 1000UL
/* Definition of timer value in ticks */
#define UTICK0_TICKS 0UL
/* UTICK0 interrupt vector ID (number). */
#define UTICK0_IRQN UTICK0_IRQn
/* BOARD_InitPeripherals defines for WWDT */
/* Definition of peripheral ID */
#define WWDT_PERIPHERAL ((WWDT_Type *) WWDT_BASE)
/* Definition of the Watchdog Timer Window value */
#define WWDT_WINDOW 16777215UL
/* Definition of the Watchdog Timer Constant value */
#define WWDT_TIMEOUT 16777215UL
/* Definition of the Watchdog Timer Warning Interrupt value */
#define WWDT_WARNING 0UL
/* WWDT interrupt vector ID (number). */
#define WWDT_IRQN WDT_BOD_IRQn
/* WWDT interrupt handler identifier. */
#define WWDT_IRQHANDLER WDT_BOD_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const i2c_master_config_t FLEXCOMM0_config;
extern const lpadc_config_t ADC0_config;
extern const usart_config_t FLEXCOMM1_config;
extern const usart_config_t FLEXCOMM2_config;
extern const wwdt_config_t WWDT_config;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
