/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: LPC55S69
package_id: LPC55S69JBD100
mcu_data: ksdk2_0
processor_version: 25.06.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 60df4a7c-b0ae-4671-8c57-ab7327174a4b
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
      - 1: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * FLEXCOMM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM0'
- type: 'flexcomm_i2c'
- mode: 'I2C_Polling'
- custom_name_enabled: 'false'
- type_id: 'flexcomm_i2c_2.0.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM0'
- config_sets:
  - fsl_i2c:
    - i2c_mode: 'kI2C_Master'
    - clockSource: 'FXCOMFunctionClock'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - i2c_master_config:
      - enableMaster: 'true'
      - baudRate_Bps: '100000'
      - enableTimeout: 'false'
    - quick_selection: 'QS_I2C_Master'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i2c_master_config_t FLEXCOMM0_config = {
  .enableMaster = true,
  .baudRate_Bps = 100000UL,
  .enableTimeout = false
};

static void FLEXCOMM0_init(void) {
  RESET_PeripheralReset( kFC0_RST_SHIFT_RSTn);
  /* Initialization function */
  I2C_MasterInit(FLEXCOMM0_PERIPHERAL, &FLEXCOMM0_config, FLEXCOMM0_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * ADC0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'ADC0'
- type: 'lpadc'
- mode: 'LPADC'
- custom_name_enabled: 'false'
- type_id: 'lpadc_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'ADC0'
- config_sets:
  - fsl_lpadc:
    - lpadcConfig:
      - clockSource: 'AsynchronousFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableInDozeMode: 'true'
      - conversionAverageMode: 'kLPADC_ConversionAverage2'
      - offsetCalibration: 'no'
      - autoCalibrate: 'false'
      - enableAnalogPreliminary: 'false'
      - powerUpDelay: '0x80'
      - referenceVoltageSource: 'kLPADC_ReferenceVoltageAlt2'
      - powerLevelMode: 'kLPADC_PowerLevelAlt1'
      - triggerPriorityPolicy: 'kLPADC_TriggerPriorityPreemptImmediately'
      - enableConvPause: 'false'
      - convPauseDelay: '0'
      - FIFO0Watermark: '0'
      - FIFO1Watermark: '0'
      - FIFO0WatermarkDMA: 'false'
      - FIFO1WatermarkDMA: 'false'
    - lpadcConvCommandConfig: []
    - lpadcConvTriggerConfig: []
    - IRQ_cfg:
      - interrupt_type: ''
      - enable_irq: 'false'
      - adc_interrupt:
        - IRQn: 'ADC0_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpadc_config_t ADC0_config = {
  .enableInDozeMode = true,
  .conversionAverageMode = kLPADC_ConversionAverage2,
  .enableAnalogPreliminary = false,
  .powerUpDelay = 0x80UL,
  .referenceVoltageSource = kLPADC_ReferenceVoltageAlt2,
  .powerLevelMode = kLPADC_PowerLevelAlt1,
  .triggerPriorityPolicy = kLPADC_TriggerPriorityPreemptImmediately,
  .enableConvPause = false,
  .convPauseDelay = 0UL,
  .FIFO0Watermark = 0UL,
  .FIFO1Watermark = 0UL
};

static void ADC0_init(void) {
  /* Initialize LPADC converter */
  LPADC_Init(ADC0_PERIPHERAL, &ADC0_config);
}

/***********************************************************************************************************************
 * PLU initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'PLU'
- type: 'plu_reg'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'plu_reg'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'PLU'
- config_sets:
  - generalConfig:
    - schema:
      - profile:
        - design: 'none'
      - active_symbols: []
      - connections: []
      - lut_data: []
    - instance_params:
      - lut_params:
        - 0: []
        - 1: []
        - 2: []
        - 3: []
        - 4: []
        - 5: []
        - 6: []
        - 7: []
        - 8: []
        - 9: []
        - 10: []
        - 11: []
        - 12: []
        - 13: []
        - 14: []
        - 15: []
        - 16: []
        - 17: []
        - 18: []
        - 19: []
        - 20: []
        - 21: []
        - 22: []
        - 23: []
        - 24: []
        - 25: []
    - out_mux_reset_uid: '1788074981039'
    - in_mux_reset_uid: '1788074981041'
    - mode_struct:
      - mode: 'schematic'
      - show_register_init: 'false'
    - resources:
      - inputs_struct:
        - inputs: []
      - outputs_struct:
        - outputs: []
      - luts_struct:
        - luts: []
    - openViewButton: '$configSet.mode_struct.mode.getValue().contains(`verilog`) ? `Apply verilog configuration` : `Open schematic view`'
    - clockSettings:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - interruptSettings:
      - LATCH_ENABLE: 'false'
      - filterConfig:
        - FILTER_MODE: '0'
        - filterClockConfig:
          - clockSource: '0'
          - clockSourceFreq: 'ClocksTool_DefaultInit'
      - MASK: ''
      - enableInterrupt: 'false'
      - interrupt:
        - IRQn: 'PLU_IRQn'
        - enable_interrrupt: 'enabled'
        - enable_priority: 'false'
        - priority: '0'
        - enable_custom_name: 'false'
    - disableClockGate: 'false'
    - plu_params: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void PLU_init(void) {
  /* Software reset of the PLU peripheral. */
  SYSCON->PRESETCTRL.PRESETCTRL2 |= SYSCON_PRESETCTRL2_PLULUT_RST_MASK;
  SYSCON->PRESETCTRL.PRESETCTRL2 &= ~SYSCON_PRESETCTRL2_PLULUT_RST_MASK;
  /* PLU wake-up/interrupt initialization */
#ifdef PLU_WAKEINT_CTRL_INIT
  PLU->WAKEINT_CTRL = PLU_WAKEINT_CTRL_INIT;
#endif /* PLU_WAKEINT_CTRL_INIT */
}

/***********************************************************************************************************************
 * SCT0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'SCT0'
- type: 'sctimer_reg'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'sctimer_reg'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'SCT0'
- config_sets:
  - sctimerConfig:
    - common_config:
      - UNIFY: '1'
      - CLKMODE: '0'
      - systemClock:
        - clockSource: 'SynchronousFunctionClock'
        - clockSourceFreq: 'ClocksTool_DefaultInit'
      - asyncClock:
        - CKSEL: '0'
        - enableUserClockFreq: 'false'
        - userClockFreq: ''
    - main:
      - SCT_L:
        - general:
          - BIDIR: '0'
          - PRE: '1'
          - STATE: '1788074981094'
          - COUNT: '0'
          - init_action: 'halt'
          - NORELOAD: 'false'
          - DRL0: 'false'
          - DRL1: 'false'
        - resources:
          - inputs: []
          - outputs: []
          - match_cap_regs: []
        - states_tab:
          - states:
            - 0:
              - uid: '1788074981094'
              - state_id: 'STATE_0'
              - state_number: '0'
              - description: ''
        - events_tab:
          - events: []
        - quick_selection: 'default'
    - enable_interrupt: 'false'
    - interrupt:
      - IRQn: 'SCT0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - sctimer_params: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void SCT0_init(void) {
  /* Software reset of the SCT0 peripheral. */
  SYSCON->PRESETCTRL.PRESETCTRL1 |= SYSCON_PRESETCTRL1_SCT_RST_MASK;
  SYSCON->PRESETCTRL.PRESETCTRL1 &= ~SYSCON_PRESETCTRL1_SCT_RST_MASK;
/****************************************************************************/
/* SCT0 general initialization */
/****************************************************************************/
/* Halt the timer */
SCT0->CTRL |= (SCT_CTRL_HALT_L_MASK | SCT_CTRL_HALT_H_MASK);

#ifdef SCT0_CONFIG_INIT
  SCT0->CONFIG = SCT0_CONFIG_INIT;
#endif /* SCT0_CONFIG_INIT */
#ifdef SCT0_DMAREQ0_INIT
  SCT0->DMAREQ0 = SCT0_DMAREQ0_INIT;
#endif /* SCT0_DMAREQ0_INIT */
#ifdef SCT0_DMAREQ1_INIT
  SCT0->DMAREQ1 = SCT0_DMAREQ1_INIT;
#endif /* SCT0_DMAREQ1_INIT */
#ifdef SCT0_EVEN_INIT
  SCT0->EVEN = SCT0_EVEN_INIT;
#endif /* SCT0_EVEN_INIT */
#ifdef SCT0_LIMIT_INIT
  SCT0->LIMIT = SCT0_LIMIT_INIT;
#endif /* SCT0_LIMIT_INIT */
#ifdef SCT0_HALT_INIT
  SCT0->HALT = SCT0_HALT_INIT;
#endif /* SCT0_HALT_INIT */
#ifdef SCT0_STOP_INIT
  SCT0->STOP = SCT0_STOP_INIT;
#endif /* SCT0_STOP_INIT */
#ifdef SCT0_START_INIT
  SCT0->START = SCT0_START_INIT;
#endif /* SCT0_START_INIT */
#ifdef SCT0_DITHER_INIT
  SCT0->DITHER = SCT0_DITHER_INIT;
#endif /* SCT0_DITHER_INIT */
#ifdef SCT0_COUNT_INIT
  SCT0->COUNT = SCT0_COUNT_INIT;
#endif /* SCT0_COUNT_INIT */
#ifdef SCT0_STATE_INIT
  SCT0->STATE = SCT0_STATE_INIT;
#endif /* SCT0_STATE_INIT */
#ifdef SCT0_OUTPUT_INIT
  SCT0->OUTPUT = SCT0_OUTPUT_INIT;
#endif /* SCT0_OUTPUT_INIT */
#ifdef SCT0_OUTPUTDIRCTRL_INIT
  SCT0->OUTPUTDIRCTRL = SCT0_OUTPUTDIRCTRL_INIT;
#endif /* SCT0_OUTPUTDIRCTRL_INIT */
#ifdef SCT0_RES_INIT
  SCT0->RES = SCT0_RES_INIT;
#endif /* SCT0_RES_INIT */
#ifdef SCT0_CONEN_INIT
  SCT0->CONEN = SCT0_CONEN_INIT;
#endif /* SCT0_CONEN_INIT */
#ifdef SCT0_REGMODE_INIT
  SCT0->REGMODE = SCT0_REGMODE_INIT;
#endif /* SCT0_REGMODE_INIT */
#ifdef SCT0_CTRL_INIT
  SCT0->CTRL = SCT0_CTRL_INIT;
#endif /* SCT0_CTRL_INIT */
}

/***********************************************************************************************************************
 * FLEXCOMM1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM1'
- type: 'flexcomm_usart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'flexcomm_usart_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM1'
- config_sets:
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t FLEXCOMM1_config = {
  .baudRate_Bps = 115200UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};

static void FLEXCOMM1_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC1_RST_SHIFT_RSTn);
  USART_Init(FLEXCOMM1_PERIPHERAL, &FLEXCOMM1_config, FLEXCOMM1_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * FLEXCOMM2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'FLEXCOMM2'
- type: 'flexcomm_usart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'flexcomm_usart_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'FLEXCOMM2'
- config_sets:
  - usartConfig_t:
    - usartConfig:
      - clockSource: 'FXCOMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - baudRate_Bps: '115200'
      - syncMode: 'kUSART_SyncModeDisabled'
      - parityMode: 'kUSART_ParityDisabled'
      - stopBitCount: 'kUSART_OneStopBit'
      - bitCountPerChar: 'kUSART_8BitsPerChar'
      - loopback: 'false'
      - txWatermark: 'kUSART_TxFifo0'
      - rxWatermark: 'kUSART_RxFifo1'
      - enableRx: 'true'
      - enableTx: 'true'
      - clockPolarity: 'kUSART_RxSampleOnFallingEdge'
      - enableContinuousSCLK: 'false'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const usart_config_t FLEXCOMM2_config = {
  .baudRate_Bps = 115200UL,
  .syncMode = kUSART_SyncModeDisabled,
  .parityMode = kUSART_ParityDisabled,
  .stopBitCount = kUSART_OneStopBit,
  .bitCountPerChar = kUSART_8BitsPerChar,
  .loopback = false,
  .txWatermark = kUSART_TxFifo0,
  .rxWatermark = kUSART_RxFifo1,
  .enableRx = true,
  .enableTx = true,
  .enableMode32k = false,
  .clockPolarity = kUSART_RxSampleOnFallingEdge,
  .enableContinuousSCLK = false
};

static void FLEXCOMM2_init(void) {
  /* Reset FLEXCOMM device */
  RESET_PeripheralReset(kFC2_RST_SHIFT_RSTn);
  USART_Init(FLEXCOMM2_PERIPHERAL, &FLEXCOMM2_config, FLEXCOMM2_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * GPIO initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'GPIO'
- type: 'lpc_gpio'
- mode: 'GPIO'
- custom_name_enabled: 'false'
- type_id: 'lpc_gpio_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'GPIO'
- config_sets:
  - lpc_gpio: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void GPIO_init(void) {
} */

/***********************************************************************************************************************
 * UTICK0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'UTICK0'
- type: 'utick'
- mode: 'general_config'
- custom_name_enabled: 'false'
- type_id: 'utick_2.0.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'UTICK0'
- config_sets:
  - fsl_utick:
    - clockSettingUTICK:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - timerSettingUTICK:
      - utick_mode_t: 'kUTICK_Onetime'
      - startTimer: 'false'
      - timerValueStr: ''
      - callbackEnable: 'false'
    - interrupt:
      - IRQn: 'UTICK0_IRQn'
      - enable_priority: 'false'
      - priority: '0'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

static void UTICK0_init(void) {
  /* UTICK0 peripheral initialization */
  UTICK_Init(UTICK0_PERIPHERAL);
  /* Configuration of UTICK0 peripheral initialization */
  UTICK_SetTick(UTICK0_PERIPHERAL, UTICK0_MODE, UTICK0_TICKS, NULL);
}

/***********************************************************************************************************************
 * WWDT initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'WWDT'
- type: 'wwdt'
- mode: 'interrupt_mode'
- custom_name_enabled: 'false'
- type_id: 'wwdt_2.1.2'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'WWDT'
- config_sets:
  - general:
    - wwdt_config:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
      - enableWwdt: 'true'
      - enableWatchdogProtect: 'false'
      - timeoutValue_input: '0xFFFFFF'
      - windowEnable: 'false'
      - warningValue_input: '0'
    - interrupt:
      - IRQn: 'WDT_BOD_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const wwdt_config_t WWDT_config = {
  .enableWwdt = true,
  .enableWatchdogReset = false,
  .enableWatchdogProtect = false,
  .windowValue = WWDT_WINDOW,
  .timeoutValue = WWDT_TIMEOUT,
  .warningValue = WWDT_WARNING,
  .clockFreq_Hz = 250000
};

static void WWDT_init(void) {
  /* WWDT initiation  */
  WWDT_Init(WWDT_PERIPHERAL, &WWDT_config);
  /* Enable interrupt WWDT_IRQN request in the NVIC */
  EnableIRQ(WWDT_IRQN);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
static void BOARD_InitPeripherals_CommonPreInit(void)
{
  /* Enable clock gate of the PLU peripheral. */
  SYSCON->AHBCLKCTRL.AHBCLKCTRL2 |= SYSCON_AHBCLKCTRL2_PLULUT_MASK;
  /* Enable clock gate of the SCT0 peripheral. */
  SYSCON->AHBCLKCTRL.AHBCLKCTRL1 |= SYSCON_AHBCLKCTRL1_SCT_MASK;
}

void BOARD_InitPeripherals(void)
{
  /* Common pre-initialization */
  BOARD_InitPeripherals_CommonPreInit();
  /* Initialize components */
  FLEXCOMM0_init();
  ADC0_init();
  PLU_init();
  SCT0_init();
  FLEXCOMM1_init();
  FLEXCOMM2_init();
  UTICK0_init();
  WWDT_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
